# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'
# カラースキーム
[[plugins]]
repo = 'gosukiwi/vim-atom-dark'
# ツリー型のファイル表示
[[plugins]]
repo = 'scrooloose/nerdtree'
# Git操作
[[plugins]]
repo = 'tpope/vim-fugitive'
# lightline
[[plugins]]
repo = 'itchyny/lightline.vim'
