# ### dein ###
[[plugins]]
repo = 'Shougo/dein.vim'
# denite
[[plugins]]
repo = 'Shougo/denite.nvim'
# ### coc ###
[[plugins]]
repo = 'neoclide/coc.nvim'
if = '''executable('node') && executable('yarn')'''
build = './install.sh nightly'

# ### 見た目 ###
# カラースキーム
[[plugins]]
repo = 'jacoborus/tender.vim'
# lightline
[[plugins]]
repo = 'itchyny/lightline.vim'
# Indent Guides
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# ### 操作 ###
# ツリー型のファイル表示
[[plugins]]
repo = 'scrooloose/nerdtree'
# 括弧補完
[[plugins]]
repo = 'cohama/lexima.vim'

# ### Git関連 ###
# Git操作
[[plugins]]
repo = 'tpope/vim-fugitive'
# 差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

